--CREATE TABLE [DS].[Employee] (
--    [Id]           VARCHAR (36)   NOT NULL,
--    [FirstName]    VARCHAR (100)  NOT NULL,
--    [MiddleName]   VARCHAR (100)  NULL,
--    [LastName]     VARCHAR (100)  NULL,
--    [EmployeeID]   INT            NULL,
--    [Email]        NVARCHAR (320) NOT NULL,
--    [Phone]        NVARCHAR (20)  NULL,
--    [HomeAddress]  NVARCHAR (100) NULL,
--    [CurrentTitle] NVARCHAR (50)  NULL,
--    [Active]       BIT            NOT NULL,
--    [CreatedBy]    NVARCHAR (256) NOT NULL,
--    [CreatedDate]  DATETIME       NOT NULL,
--    [Updatedby]    NVARCHAR (256) NULL,
--    [UpdatedDate]  DATETIME       NULL,
--    PRIMARY KEY CLUSTERED ([Id] ASC)
--);

